"""Add is_onboarded field to users table

Revision ID: 1907ea36b78e
Revises: b0a75746d298
Create Date: 2026-02-11 20:06:40.065856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1907ea36b78e'
down_revision: Union[str, Sequence[str], None] = 'b0a75746d298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_onboarded')
    # ### end Alembic commands ###
